// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/section"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SectionCreate is the builder for creating a Section entity.
type SectionCreate struct {
	config
	mutation *SectionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (sc *SectionCreate) SetCreatedAt(t time.Time) *SectionCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SectionCreate) SetNillableCreatedAt(t *time.Time) *SectionCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *SectionCreate) SetUpdatedAt(t time.Time) *SectionCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *SectionCreate) SetNillableUpdatedAt(t *time.Time) *SectionCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetDeletedAt sets the "deleted_at" field.
func (sc *SectionCreate) SetDeletedAt(t time.Time) *SectionCreate {
	sc.mutation.SetDeletedAt(t)
	return sc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sc *SectionCreate) SetNillableDeletedAt(t *time.Time) *SectionCreate {
	if t != nil {
		sc.SetDeletedAt(*t)
	}
	return sc
}

// SetSectionName sets the "section_name" field.
func (sc *SectionCreate) SetSectionName(s string) *SectionCreate {
	sc.mutation.SetSectionName(s)
	return sc
}

// SetStatement sets the "statement" field.
func (sc *SectionCreate) SetStatement(s string) *SectionCreate {
	sc.mutation.SetStatement(s)
	return sc
}

// SetNillableStatement sets the "statement" field if the given value is not nil.
func (sc *SectionCreate) SetNillableStatement(s *string) *SectionCreate {
	if s != nil {
		sc.SetStatement(*s)
	}
	return sc
}

// SetManagerID sets the "manager_id" field.
func (sc *SectionCreate) SetManagerID(i int64) *SectionCreate {
	sc.mutation.SetManagerID(i)
	return sc
}

// SetID sets the "id" field.
func (sc *SectionCreate) SetID(i int64) *SectionCreate {
	sc.mutation.SetID(i)
	return sc
}

// Mutation returns the SectionMutation object of the builder.
func (sc *SectionCreate) Mutation() *SectionMutation {
	return sc.mutation
}

// Save creates the Section in the database.
func (sc *SectionCreate) Save(ctx context.Context) (*Section, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SectionCreate) SaveX(ctx context.Context) *Section {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SectionCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SectionCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SectionCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := section.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := section.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SectionCreate) check() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Section.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Section.updated_at"`)}
	}
	if _, ok := sc.mutation.SectionName(); !ok {
		return &ValidationError{Name: "section_name", err: errors.New(`ent: missing required field "Section.section_name"`)}
	}
	if v, ok := sc.mutation.SectionName(); ok {
		if err := section.SectionNameValidator(v); err != nil {
			return &ValidationError{Name: "section_name", err: fmt.Errorf(`ent: validator failed for field "Section.section_name": %w`, err)}
		}
	}
	if v, ok := sc.mutation.Statement(); ok {
		if err := section.StatementValidator(v); err != nil {
			return &ValidationError{Name: "statement", err: fmt.Errorf(`ent: validator failed for field "Section.statement": %w`, err)}
		}
	}
	if _, ok := sc.mutation.ManagerID(); !ok {
		return &ValidationError{Name: "manager_id", err: errors.New(`ent: missing required field "Section.manager_id"`)}
	}
	if v, ok := sc.mutation.ManagerID(); ok {
		if err := section.ManagerIDValidator(v); err != nil {
			return &ValidationError{Name: "manager_id", err: fmt.Errorf(`ent: validator failed for field "Section.manager_id": %w`, err)}
		}
	}
	if v, ok := sc.mutation.ID(); ok {
		if err := section.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Section.id": %w`, err)}
		}
	}
	return nil
}

func (sc *SectionCreate) sqlSave(ctx context.Context) (*Section, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SectionCreate) createSpec() (*Section, *sqlgraph.CreateSpec) {
	var (
		_node = &Section{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(section.Table, sqlgraph.NewFieldSpec(section.FieldID, field.TypeInt64))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(section.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(section.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.DeletedAt(); ok {
		_spec.SetField(section.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := sc.mutation.SectionName(); ok {
		_spec.SetField(section.FieldSectionName, field.TypeString, value)
		_node.SectionName = value
	}
	if value, ok := sc.mutation.Statement(); ok {
		_spec.SetField(section.FieldStatement, field.TypeString, value)
		_node.Statement = &value
	}
	if value, ok := sc.mutation.ManagerID(); ok {
		_spec.SetField(section.FieldManagerID, field.TypeInt64, value)
		_node.ManagerID = value
	}
	return _node, _spec
}

// SectionCreateBulk is the builder for creating many Section entities in bulk.
type SectionCreateBulk struct {
	config
	err      error
	builders []*SectionCreate
}

// Save creates the Section entities in the database.
func (scb *SectionCreateBulk) Save(ctx context.Context) ([]*Section, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Section, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SectionCreateBulk) SaveX(ctx context.Context) []*Section {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SectionCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SectionCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
