// Code generated by ent, DO NOT EDIT.

package voteevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the voteevent type in the database.
	Label = "vote_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldFromRoleID holds the string denoting the from_role_id field in the database.
	FieldFromRoleID = "from_role_id"
	// FieldToVoteID holds the string denoting the to_vote_id field in the database.
	FieldToVoteID = "to_vote_id"
	// FieldToVoteOption holds the string denoting the to_vote_option field in the database.
	FieldToVoteOption = "to_vote_option"
	// Table holds the table name of the voteevent in the database.
	Table = "vote_events"
)

// Columns holds all SQL columns for voteevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldFromRoleID,
	FieldToVoteID,
	FieldToVoteOption,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UpdateDefaultDeletedAt holds the default value on update for the "deleted_at" field.
	UpdateDefaultDeletedAt func() time.Time
	// FromRoleIDValidator is a validator for the "from_role_id" field. It is called by the builders before save.
	FromRoleIDValidator func(int64) error
	// ToVoteIDValidator is a validator for the "to_vote_id" field. It is called by the builders before save.
	ToVoteIDValidator func(int64) error
	// ToVoteOptionValidator is a validator for the "to_vote_option" field. It is called by the builders before save.
	ToVoteOptionValidator func(int64) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the VoteEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByFromRoleID orders the results by the from_role_id field.
func ByFromRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromRoleID, opts...).ToFunc()
}

// ByToVoteID orders the results by the to_vote_id field.
func ByToVoteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToVoteID, opts...).ToFunc()
}

// ByToVoteOption orders the results by the to_vote_option field.
func ByToVoteOption(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToVoteOption, opts...).ToFunc()
}
