// Code generated by ent, DO NOT EDIT.

package voteevent

import (
	"backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldDeletedAt, v))
}

// FromRoleID applies equality check predicate on the "from_role_id" field. It's identical to FromRoleIDEQ.
func FromRoleID(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldFromRoleID, v))
}

// ToVoteID applies equality check predicate on the "to_vote_id" field. It's identical to ToVoteIDEQ.
func ToVoteID(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldToVoteID, v))
}

// ToVoteOption applies equality check predicate on the "to_vote_option" field. It's identical to ToVoteOptionEQ.
func ToVoteOption(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldToVoteOption, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNotNull(FieldDeletedAt))
}

// FromRoleIDEQ applies the EQ predicate on the "from_role_id" field.
func FromRoleIDEQ(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldFromRoleID, v))
}

// FromRoleIDNEQ applies the NEQ predicate on the "from_role_id" field.
func FromRoleIDNEQ(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNEQ(FieldFromRoleID, v))
}

// FromRoleIDIn applies the In predicate on the "from_role_id" field.
func FromRoleIDIn(vs ...int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldIn(FieldFromRoleID, vs...))
}

// FromRoleIDNotIn applies the NotIn predicate on the "from_role_id" field.
func FromRoleIDNotIn(vs ...int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNotIn(FieldFromRoleID, vs...))
}

// FromRoleIDGT applies the GT predicate on the "from_role_id" field.
func FromRoleIDGT(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGT(FieldFromRoleID, v))
}

// FromRoleIDGTE applies the GTE predicate on the "from_role_id" field.
func FromRoleIDGTE(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGTE(FieldFromRoleID, v))
}

// FromRoleIDLT applies the LT predicate on the "from_role_id" field.
func FromRoleIDLT(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLT(FieldFromRoleID, v))
}

// FromRoleIDLTE applies the LTE predicate on the "from_role_id" field.
func FromRoleIDLTE(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLTE(FieldFromRoleID, v))
}

// ToVoteIDEQ applies the EQ predicate on the "to_vote_id" field.
func ToVoteIDEQ(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldToVoteID, v))
}

// ToVoteIDNEQ applies the NEQ predicate on the "to_vote_id" field.
func ToVoteIDNEQ(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNEQ(FieldToVoteID, v))
}

// ToVoteIDIn applies the In predicate on the "to_vote_id" field.
func ToVoteIDIn(vs ...int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldIn(FieldToVoteID, vs...))
}

// ToVoteIDNotIn applies the NotIn predicate on the "to_vote_id" field.
func ToVoteIDNotIn(vs ...int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNotIn(FieldToVoteID, vs...))
}

// ToVoteIDGT applies the GT predicate on the "to_vote_id" field.
func ToVoteIDGT(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGT(FieldToVoteID, v))
}

// ToVoteIDGTE applies the GTE predicate on the "to_vote_id" field.
func ToVoteIDGTE(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGTE(FieldToVoteID, v))
}

// ToVoteIDLT applies the LT predicate on the "to_vote_id" field.
func ToVoteIDLT(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLT(FieldToVoteID, v))
}

// ToVoteIDLTE applies the LTE predicate on the "to_vote_id" field.
func ToVoteIDLTE(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLTE(FieldToVoteID, v))
}

// ToVoteOptionEQ applies the EQ predicate on the "to_vote_option" field.
func ToVoteOptionEQ(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldEQ(FieldToVoteOption, v))
}

// ToVoteOptionNEQ applies the NEQ predicate on the "to_vote_option" field.
func ToVoteOptionNEQ(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNEQ(FieldToVoteOption, v))
}

// ToVoteOptionIn applies the In predicate on the "to_vote_option" field.
func ToVoteOptionIn(vs ...int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldIn(FieldToVoteOption, vs...))
}

// ToVoteOptionNotIn applies the NotIn predicate on the "to_vote_option" field.
func ToVoteOptionNotIn(vs ...int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldNotIn(FieldToVoteOption, vs...))
}

// ToVoteOptionGT applies the GT predicate on the "to_vote_option" field.
func ToVoteOptionGT(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGT(FieldToVoteOption, v))
}

// ToVoteOptionGTE applies the GTE predicate on the "to_vote_option" field.
func ToVoteOptionGTE(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldGTE(FieldToVoteOption, v))
}

// ToVoteOptionLT applies the LT predicate on the "to_vote_option" field.
func ToVoteOptionLT(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLT(FieldToVoteOption, v))
}

// ToVoteOptionLTE applies the LTE predicate on the "to_vote_option" field.
func ToVoteOptionLTE(v int64) predicate.VoteEvent {
	return predicate.VoteEvent(sql.FieldLTE(FieldToVoteOption, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VoteEvent) predicate.VoteEvent {
	return predicate.VoteEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VoteEvent) predicate.VoteEvent {
	return predicate.VoteEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VoteEvent) predicate.VoteEvent {
	return predicate.VoteEvent(sql.NotPredicates(p))
}
